language: scala
scala:
  - 2.10.6
  - 2.11.8
jdk: oraclejdk7

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

script:
  - if [[ "${TRAVIS_SCALA_VERSION%.*}" == "2.10" ]]; then
      sbt ++$TRAVIS_SCALA_VERSION clean test;
    else
      sbt ++$TRAVIS_SCALA_VERSION clean scalastyle coverage test coverageReport coverageAggregate;
    fi

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - neville@spotify.com
